# Generated by Django 3.0.8 on 2020-08-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('date', models.DateField(max_length=10)),
                ('time', models.TimeField(blank=True, null=True)),
                ('phone_number', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('subject', models.TextField(max_length=250, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
