# Generated by Django 3.0.8 on 2020-08-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200827_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
