# Generated by Django 3.0.8 on 2020-08-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_appointment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='message',
        ),
    ]
